### PR TITLE
85 vignette describing how individual planes components work

### PR DESCRIPTION
**Pull request by abenefield1**
I understand why we got rid of the specific function arguments in the basic usage vignette, but I'd like to keep them here, because where there are different options (e.g., sig_lvl for trend, and tolderance for repeat), I run through examples where we change those thresholds to show how they are used.

### CODE REVIEW

**Review by vpnagraj — APPROVED** [review]

**Comment by vpnagraj** [comment]
@abenefield1 i've reviewed the vignette you drafted. general structure is largely the same. but i have gone ahead and refactored the content to use mock data instead of the built in examples. i think this gives us a little more flexibility to show how the components work. i also made text changes throughout and a few minor changes to plot. renamed the vignette as planes-components.Rmd too. 

please give this one more look and comment back here if its good to go.

once i hear back from you i will merge into dev

**Comment by vpnagraj** [comment]
@abenefield1 pinging you again here for a quick read through the updated vignettes. thanks!

**Comment by abenefield1** [comment]
Oops, thanks! I started looking at this Thursday afternoon and then completely forgot about it. Should be able to get it done before our meeting tomorrow.

**Comment by vpnagraj** [comment]
agree on all points @abenefield1 . can you take a crack at fixing?

and to the last suggestion ... i honestly cant remember if there was a change point flagged in the time series outside of the evaluated window. i guess we could toggle to sig_lvl to get one to pop up? but id like to avoid creating any fake observed data just for that if possible.

**Comment by abenefield1** [comment]
@vpnagraj will do. No need to create a new branch, right?

I know there were a few locations where that happened (changepoint flagged in observed), so we can use that.

**Comment by vpnagraj** [comment]
correct! no need to create a new branch. push directly here and it will update the PR.

**Comment by abenefield1** [comment]
@vpnagraj  - I made the edits we discussed. Take a look when you can!

**Comment by vpnagraj** [comment]
a few more minor edits on top of yours @abenefield1 ... looks good to go. merging!

**Pull request merged**
